spring:
  application:
    name: RagBasedApplication

  data:
    mongodb:
      uri: <YOUR_MONGODB_URI>

langchain4j:
  google-ai:
    gemini:
      api-key: <YOUR_GEMINI_API_KEY>
      model-name: gemini-2.5-flash


server:
  port: 8080
  servlet:
    context-path: /api